In [1]:
"""

This is for morphological classification of galaxies by CNN,
By Kenji Bekki, on 2020/2/14 for Nair & Abraham 2010

"""


import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
from keras.utils import np_utils
from keras.models import model_from_json
import keras.callbacks
import numpy as np
#import keras.backend.tensorflow_backend as KTF
#import tensorflow as tf
import os.path


### Total model number = (nmodle0) * nmodel

#iset=int(input('Input the total number of sets of models '))
#nmodel0=int(input('Input the total number of images per model'))
#nmodel=nmodel0*iset
nmodel=2458
print('nmodel',nmodel)

### Original values
#batch_size = 128
#num_classes = 10
#epochs = 12
batch_size = 100
#num_classes = 5
num_classes = 3
epochs = 400
nb_epoch=epochs
n_mesh=50
#nmodel=1000
print('nmodel',nmodel)
print('num_classes',num_classes)

img_rows, img_cols = n_mesh, n_mesh
n_mesh2=n_mesh*n_mesh-1
n_mesh3=n_mesh*n_mesh


print(img_rows, img_cols, n_mesh2)
#stop



#(x_train, y_train), (x_test, y_test) = mnist.load_data()
#x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
#x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)

input_shape = (img_rows, img_cols, 1)

#x_train = x_train.astype('float32')
#x_test = x_test.astype('float32')
#x_train /= 255
#x_test /= 255
#print('x_train shape:', x_train.shape)
#print(x_train.shape[0], 'train samples')
#print(x_test.shape[0], 'test samples')
#print(y_test.shape[0], 'y.test samples')
#print(str(y_test[0]))
#print(str(y_test[1]))
#print(str(y_test[2]))

#y_train = y_train.astype('int32')
#y_test = y_test.astype('int32')
#y_train = keras.utils.np_utils.to_categorical(y_train, num_classes)
#y_test =  keras.utils.np_utils.to_categorical(y_test, num_classes)

# This is for simlation data sets

with open('2dft.dat') as f:
  lines=f.readlines()
with open('2dftn.dat') as f:
  lines1=f.readlines()


x_train=np.zeros((nmodel,n_mesh3))
x_test=np.zeros((nmodel,n_mesh3))
y_train=np.zeros(nmodel,dtype=np.int)
y_test=np.zeros(nmodel,dtype=np.int)
#y_test=np.zeros(nmodel)
#print(y_train)

# For 2D density map data
ibin=0
jbin=-1
for num,j in enumerate(lines):
  jbin=jbin+1
  tm=j.strip().split()
  x_train[ibin,jbin]=float(tm[0])
  x_test[ibin,jbin]=float(tm[0])
#  print('ibin,jbin',ibin,jbin)
  if jbin == n_mesh2:
    ibin+=1
    jbin=-1

# For morphological map
ibin=0
for num,j in enumerate(lines1):
  tm=j.strip().split()
  y_train[ibin]=int(tm[0])-1
  y_test[ibin]=int(tm[0])-1
#  print('ibin, (Morpholigcl type)',ibin,y_train[ibin])
  ibin+=1




x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)
y_train = keras.utils.np_utils.to_categorical(y_train, num_classes)
y_test =  keras.utils.np_utils.to_categorical(y_test, num_classes)

print('Galaxy type',y_train[:5])

#stop

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs,
          verbose=1, validation_data=(x_test, y_test))

score = model.evaluate(x_test, y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])


print('save the architecture of a model')

model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)

# serialize weights to HDF5
model.save_weights("model.h5")
print("Saved model to disk")


nmodel 2458
nmodel 2458
num_classes 3
50 50 2499
Galaxy type [[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]]
Epoch 1/400
25/25 [==============================] - 3s 60ms/step - loss: 1.0938 - accuracy: 0.4353 - val_loss: 1.0670 - val_accuracy: 0.6880
Epoch 2/400
25/25 [==============================] - 1s 22ms/step - loss: 1.0654 - accuracy: 0.5269 - val_loss: 1.0409 - val_accuracy: 0.6656
Epoch 3/400
25/25 [==============================] - 1s 22ms/step - loss: 1.0438 - accuracy: 0.5433 - val_loss: 1.0185 - val_accuracy: 0.6656
Epoch 4/400
25/25 [==============================] - 1s 22ms/step - loss: 1.0203 - accuracy: 0.5902 - val_loss: 1.0000 - val_accuracy: 0.6656
Epoch 5/400
25/25 [==============================] - 1s 22ms/step - loss: 1.0032 - accuracy: 0.5736 - val_loss: 0.9838 - val_accuracy: 0.6656
Epoch 6/400
25/25 [==============================] - 1s 22ms/step - loss: 0.9883 - accuracy: 0.6369 - val_loss: 0.9680 - val_accuracy: 0.6656
Epoch 7/400
25/25 [=======

25/25 [==============================] - 1s 22ms/step - loss: 0.5760 - accuracy: 0.6889 - val_loss: 0.5456 - val_accuracy: 0.8784
Epoch 58/400
25/25 [==============================] - 1s 22ms/step - loss: 0.5807 - accuracy: 0.6890 - val_loss: 0.5418 - val_accuracy: 0.8564
Epoch 59/400
25/25 [==============================] - 1s 22ms/step - loss: 0.5768 - accuracy: 0.6813 - val_loss: 0.5383 - val_accuracy: 0.8959
Epoch 60/400
25/25 [==============================] - 1s 22ms/step - loss: 0.5751 - accuracy: 0.6902 - val_loss: 0.5349 - val_accuracy: 0.8592
Epoch 61/400
25/25 [==============================] - 1s 22ms/step - loss: 0.5550 - accuracy: 0.7117 - val_loss: 0.5316 - val_accuracy: 0.8731
Epoch 62/400
25/25 [==============================] - 1s 22ms/step - loss: 0.5483 - accuracy: 0.7319 - val_loss: 0.5282 - val_accuracy: 0.8743
Epoch 63/400
25/25 [==============================] - 1s 22ms/step - loss: 0.5623 - accuracy: 0.6890 - val_loss: 0.5253 - val_accuracy: 0.8861
Epoch 64/400

25/25 [==============================] - 1s 22ms/step - loss: 0.4773 - accuracy: 0.7319 - val_loss: 0.4440 - val_accuracy: 0.9239
Epoch 115/400
25/25 [==============================] - 1s 22ms/step - loss: 0.4818 - accuracy: 0.7239 - val_loss: 0.4431 - val_accuracy: 0.9268
Epoch 116/400
25/25 [==============================] - 1s 22ms/step - loss: 0.4738 - accuracy: 0.7242 - val_loss: 0.4422 - val_accuracy: 0.9239
Epoch 117/400
25/25 [==============================] - 1s 22ms/step - loss: 0.4841 - accuracy: 0.7190 - val_loss: 0.4412 - val_accuracy: 0.9296
Epoch 118/400
25/25 [==============================] - 1s 22ms/step - loss: 0.4581 - accuracy: 0.7406 - val_loss: 0.4403 - val_accuracy: 0.9219
Epoch 119/400
25/25 [==============================] - 1s 22ms/step - loss: 0.4745 - accuracy: 0.7166 - val_loss: 0.4394 - val_accuracy: 0.9264
Epoch 120/400
25/25 [==============================] - 1s 22ms/step - loss: 0.4813 - accuracy: 0.7201 - val_loss: 0.4386 - val_accuracy: 0.9292
Epoch 

Epoch 171/400
25/25 [==============================] - 1s 23ms/step - loss: 0.4276 - accuracy: 0.7839 - val_loss: 0.3991 - val_accuracy: 0.9288
Epoch 172/400
25/25 [==============================] - 1s 24ms/step - loss: 0.4230 - accuracy: 0.7806 - val_loss: 0.3983 - val_accuracy: 0.9312
Epoch 173/400
25/25 [==============================] - 1s 24ms/step - loss: 0.4246 - accuracy: 0.7761 - val_loss: 0.3976 - val_accuracy: 0.9296
Epoch 174/400
25/25 [==============================] - 1s 23ms/step - loss: 0.4310 - accuracy: 0.7785 - val_loss: 0.3969 - val_accuracy: 0.9337
Epoch 175/400
25/25 [==============================] - 1s 23ms/step - loss: 0.4347 - accuracy: 0.7702 - val_loss: 0.3963 - val_accuracy: 0.9296
Epoch 176/400
25/25 [==============================] - 1s 28ms/step - loss: 0.4340 - accuracy: 0.7684 - val_loss: 0.3956 - val_accuracy: 0.9296
Epoch 177/400
25/25 [==============================] - 1s 22ms/step - loss: 0.4196 - accuracy: 0.7762 - val_loss: 0.3949 - val_accuracy:

Epoch 228/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3968 - accuracy: 0.8236 - val_loss: 0.3619 - val_accuracy: 0.9272
Epoch 229/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3976 - accuracy: 0.8102 - val_loss: 0.3611 - val_accuracy: 0.9353
Epoch 230/400
25/25 [==============================] - 1s 23ms/step - loss: 0.3945 - accuracy: 0.8234 - val_loss: 0.3605 - val_accuracy: 0.9353
Epoch 231/400
25/25 [==============================] - 1s 23ms/step - loss: 0.3900 - accuracy: 0.8171 - val_loss: 0.3599 - val_accuracy: 0.9353
Epoch 232/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3889 - accuracy: 0.8261 - val_loss: 0.3593 - val_accuracy: 0.9304
Epoch 233/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3946 - accuracy: 0.8081 - val_loss: 0.3586 - val_accuracy: 0.9349
Epoch 234/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3890 - accuracy: 0.8218 - val_loss: 0.3580 - val_accuracy:

Epoch 285/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3703 - accuracy: 0.8333 - val_loss: 0.3254 - val_accuracy: 0.9353
Epoch 286/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3522 - accuracy: 0.8612 - val_loss: 0.3248 - val_accuracy: 0.9410
Epoch 287/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3685 - accuracy: 0.8515 - val_loss: 0.3242 - val_accuracy: 0.9353
Epoch 288/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3513 - accuracy: 0.8573 - val_loss: 0.3236 - val_accuracy: 0.9410
Epoch 289/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3599 - accuracy: 0.8493 - val_loss: 0.3231 - val_accuracy: 0.9353
Epoch 290/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3551 - accuracy: 0.8534 - val_loss: 0.3222 - val_accuracy: 0.9467
Epoch 291/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3441 - accuracy: 0.8654 - val_loss: 0.3215 - val_accuracy:

Epoch 342/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3212 - accuracy: 0.8856 - val_loss: 0.2891 - val_accuracy: 0.9662
Epoch 343/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3257 - accuracy: 0.8724 - val_loss: 0.2884 - val_accuracy: 0.9723
Epoch 344/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3291 - accuracy: 0.8743 - val_loss: 0.2878 - val_accuracy: 0.9972
Epoch 345/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3370 - accuracy: 0.8609 - val_loss: 0.2870 - val_accuracy: 0.9821
Epoch 346/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3280 - accuracy: 0.8658 - val_loss: 0.2864 - val_accuracy: 0.9805
Epoch 347/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3218 - accuracy: 0.8878 - val_loss: 0.2857 - val_accuracy: 0.9894
Epoch 348/400
25/25 [==============================] - 1s 22ms/step - loss: 0.3205 - accuracy: 0.8796 - val_loss: 0.2851 - val_accuracy:

Epoch 399/400
25/25 [==============================] - 1s 25ms/step - loss: 0.2920 - accuracy: 0.8958 - val_loss: 0.2531 - val_accuracy: 1.0000
Epoch 400/400
25/25 [==============================] - 1s 22ms/step - loss: 0.2934 - accuracy: 0.8984 - val_loss: 0.2525 - val_accuracy: 1.0000
Test score: 0.25247904658317566
Test accuracy: 1.0
save the architecture of a model
Saved model to disk
