In [13]:
import keras
from keras.datasets import mnist
from keras.models import Sequential
from keras.layers import Dense, Dropout, Flatten
from keras.layers import Conv2D, MaxPooling2D
from keras import backend as K
from keras.utils import np_utils
from keras.models import model_from_json
import keras.callbacks
import numpy as np
#import keras.backend.tensorflow_backend as KTF
#import tensorflow as tf
import os.path

In [14]:
### Total model number = (nmodle0) * nmodel

#iset=int(input('Input the total number of sets of models '))
#nmodel0=int(input('Input the total number of images per model'))
#nmodel=nmodel0*iset
nmodel=2458
print('nmodel',nmodel)

nmodel 2458


In [15]:
### Original values
#batch_size = 128
#num_classes = 10
#epochs = 30
batch_size = 100
#num_classes = 5
num_classes = 3
epochs = 30
nb_epoch=epochs
n_mesh=50
#nmodel=1000
print('nmodel', nmodel)
print('num_classes', num_classes)


nmodel 2458
num_classes 3


In [16]:
img_rows, img_cols = n_mesh, n_mesh
n_mesh2=n_mesh*n_mesh-1
n_mesh3=n_mesh*n_mesh

In [17]:
print(img_rows, img_cols, n_mesh2)
#stop

50 50 2499


In [18]:
#(x_train, y_train), (x_test, y_test) = mnist.load_data()
#x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
#x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)

input_shape = (img_rows, img_cols, 1)
print(input_shape)

(50, 50, 1)


In [19]:
#x_train = x_train.astype('float32')
#x_test = x_test.astype('float32')
#x_train /= 255
#x_test /= 255
#print('x_train shape:', x_train.shape)
#print(x_train.shape[0], 'train samples')
#print(x_test.shape[0], 'test samples')
#print(y_test.shape[0], 'y.test samples')
#print(str(y_test[0]))
#print(str(y_test[1]))
#print(str(y_test[2]))

#y_train = y_train.astype('int32')
#y_test = y_test.astype('int32')
#y_train = keras.utils.np_utils.to_categorical(y_train, num_classes)
#y_test =  keras.utils.np_utils.to_categorical(y_test, num_classes)

In [20]:
# This is for simlation data sets

with open('2dft.dat') as f: # Image files
  lines=f.readlines()
with open('2dftn.dat') as f: # Labels
  lines1=f.readlines()

In [21]:
x_train=np.zeros((nmodel,n_mesh3))
x_test=np.zeros((nmodel,n_mesh3))
y_train=np.zeros(nmodel,dtype=np.int)
y_test=np.zeros(nmodel,dtype=np.int)
#y_test=np.zeros(nmodel)
#print(y_train)

In [22]:
# For 2D density map data
ibin=0
jbin=-1
for num,j in enumerate(lines):
  jbin=jbin+1
  tm=j.strip().split()
  x_train[ibin,jbin]=float(tm[0])
  x_test[ibin,jbin]=float(tm[0])
#  print('ibin,jbin',ibin,jbin)
  if jbin == n_mesh2:
    ibin+=1
    jbin=-1

In [23]:
# For morphological map
ibin=0
for num,j in enumerate(lines1):
  tm=j.strip().split()
  y_train[ibin]=int(tm[0])-1
  y_test[ibin]=int(tm[0])-1
  #print('ibin, (Morpholigcl type)',ibin,y_train[ibin])
  ibin+=1

In [24]:
x_train = x_train.reshape(x_train.shape[0], img_rows, img_cols, 1)
x_test = x_test.reshape(x_test.shape[0], img_rows, img_cols, 1)

print(x_train.shape)
print(x_test.shape)

print(y_train)

y_train = keras.utils.np_utils.to_categorical(y_train, num_classes)
y_test =  keras.utils.np_utils.to_categorical(y_test, num_classes)

print(y_train.shape)
print(y_test.shape)

print('Galaxy type',y_train)

(2458, 50, 50, 1)
(2458, 50, 50, 1)
[0 0 0 ... 2 2 2]
(2458, 3)
(2458, 3)
Galaxy type [[1. 0. 0.]
 [1. 0. 0.]
 [1. 0. 0.]
 ...
 [0. 0. 1.]
 [0. 0. 1.]
 [0. 0. 1.]]


In [13]:
#stop

model = Sequential()
model.add(Conv2D(32, kernel_size=(3, 3),
                 activation='relu',
                 input_shape=input_shape))
model.add(Conv2D(64, (3, 3), activation='relu'))
model.add(MaxPooling2D(pool_size=(2, 2)))
model.add(Dropout(0.25))
model.add(Flatten())
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.5))
model.add(Dense(num_classes, activation='softmax'))

model.compile(loss=keras.losses.categorical_crossentropy,
              optimizer=keras.optimizers.Adadelta(),
              metrics=['accuracy'])

model.fit(x_train, y_train, batch_size=batch_size, epochs=epochs,
          verbose=1, validation_data=(x_test, y_test))

score = model.evaluate(x_test, y_test, verbose=0)
print('Test score:', score[0])
print('Test accuracy:', score[1])

Epoch 1/30
25/25 [==============================] - 3s 60ms/step - loss: 1.0896 - accuracy: 0.4127 - val_loss: 1.0751 - val_accuracy: 0.3344
Epoch 2/30
25/25 [==============================] - 1s 22ms/step - loss: 1.0744 - accuracy: 0.4556 - val_loss: 1.0594 - val_accuracy: 0.6041
Epoch 3/30
25/25 [==============================] - 1s 22ms/step - loss: 1.0598 - accuracy: 0.4790 - val_loss: 1.0444 - val_accuracy: 0.6680
Epoch 4/30
25/25 [==============================] - 1s 22ms/step - loss: 1.0422 - accuracy: 0.5065 - val_loss: 1.0294 - val_accuracy: 0.6680
Epoch 5/30
25/25 [==============================] - 1s 22ms/step - loss: 1.0296 - accuracy: 0.5313 - val_loss: 1.0134 - val_accuracy: 0.6680
Epoch 6/30
25/25 [==============================] - 1s 22ms/step - loss: 1.0174 - accuracy: 0.5452 - val_loss: 0.9977 - val_accuracy: 0.6680
Epoch 7/30
25/25 [==============================] - 1s 30ms/step - loss: 1.0002 - accuracy: 0.6038 - val_loss: 0.9825 - val_accuracy: 0.6680
Epoch 8/30
25

In [14]:
print('save the architecture of a model')

model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)

# serialize weights to HDF5
model.save_weights("model.h5")
print("Saved model to disk")


save the architecture of a model
Saved model to disk


In [15]:
import tensorflow as tf
print("Num GPUs Available: ", len(tf.config.experimental.list_physical_devices('GPU')))


Num GPUs Available:  1
